version: '3'

services:  
  client:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./index.html:/usr/src/index.html:ro
      - ./public:/usr/src/public:ro
      - ./src:/usr/src/src:ro
